//=============================================================================
// Brief   : Binding Cache
// Authors : Bruno Santos <bsantos@av.it.pt>
// ----------------------------------------------------------------------------
// OPMIP - Open Proxy Mobile IP
//
// Copyright (C) 2010 Universidade de Aveiro
// Copyrigth (C) 2010 Instituto de Telecomunicações - Pólo de Aveiro
//
// This software is distributed under a license. The full license
// agreement can be found in the file LICENSE in this distribution.
// This software may not be copied, modified, sold or distributed
// other than expressed in the named license agreement.
//
// This software is distributed without any warranty.
//=============================================================================

#ifndef OPMIP_PMIP_BCACHE__HPP_
#define OPMIP_PMIP_BCACHE__HPP_

///////////////////////////////////////////////////////////////////////////////
#include <opmip/base.hpp>
#include <opmip/ip/address.hpp>
#include <opmip/ip/prefix.hpp>
#include <opmip/ll/technology.hpp>
#include <opmip/ll/mac_address.hpp>
#include <boost/intrusive/rbtree.hpp>
#include <string>
#include <vector>
#include <list>

///////////////////////////////////////////////////////////////////////////////
namespace opmip { namespace pmip {

///////////////////////////////////////////////////////////////////////////////
class bcache_entry {
	friend class bcache;

public:
	typedef ip::address_v6        net_address;
	typedef ip::prefix_v6         net_prefix;
	typedef std::list<net_prefix> net_prefix_list;
	typedef std::string           net_access_id;
	typedef std::vector<uint8>    link_id;
	typedef ll::technology        link_type;
	typedef ll::mac_address       link_address;
	typedef uint                  tunnel_id;

public:
	bcache_entry()
	{ }

private:
	boost::intrusive::set_member_hook<> _hook;

protected:
	net_address      _mn_home_addr;     ///MN Home Address
	net_address      _mn_care_of_addr;  ///MN Care of Address
	net_access_id    _mn_id;            ///MN Identifier
	link_id          _mn_link_id;       ///MN Link Identifier
	link_address     _mag_pp_link_addr; ///MAG P-to-P Local Link Address generated by the LMA after accepting the initial PBU
	uint64           _lifetime;         ///Remaining lifetime of this entry from last binding update
	bool             _is_home_reg;      ///Home registration flag
	bool             _is_proxy_reg;     ///Proxy registration flag
	uint16           _sequence_num;     ///Sequence Number from last binding update, see also section 9.5.1
	net_prefix_list  _net_prefixes;     ///MN List of Network Prefixes
	tunnel_id        _tunnel;           ///Tunnel Identifier
	link_type        _mn_link_type;     ///MN Link-Layer Technology
	uint64           _bu_timestamp;     ///Last BU Timestamp
};

///////////////////////////////////////////////////////////////////////////////
class bcache {
	struct compare {
		bool operator()(const bcache_entry& rhs, const bcache_entry& lhs) const
		{
			return rhs._mn_id < lhs._mn_id;
		}

		bool operator()(const bcache_entry& rhs, const bcache_entry::net_access_id& key) const
		{
			return rhs._mn_id < key;
		}

		bool operator()(const bcache_entry::net_access_id& key, const bcache_entry& lhs) const
		{
			return key < lhs._mn_id;
		}
	};

	typedef boost::intrusive::compare<compare> compare_option;

	typedef boost::intrusive::member_hook<bcache_entry,
	                                      boost::intrusive::set_member_hook<>,
	                                      &bcache_entry::_hook> member_hook_option;

public:
	typedef boost::intrusive::rbtree<bcache_entry,
	                                 member_hook_option,
	                                 compare_option> type;

	typedef bcache_entry                  entry_type;
	typedef bcache_entry::net_address     net_address;
	typedef bcache_entry::net_prefix      net_prefix;
	typedef bcache_entry::net_prefix_list net_prefix_list;
	typedef bcache_entry::net_access_id   net_access_id;
	typedef bcache_entry::link_id         link_id;
	typedef bcache_entry::link_type       link_type;
	typedef bcache_entry::link_address    link_address;
	typedef bcache_entry::tunnel_id       tunnel_id;
};

///////////////////////////////////////////////////////////////////////////////
} /* namespace pmip */ } /* namespace opmip */

///////////////////////////////////////////////////////////////////////////////
#endif /* OPMIP_PMIP_BCACHE__HPP_ */
